/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ./shirt_trader.glb --simplify --keepmeshes --types 
*/

import * as THREE from "three";
import { useAnimations, useFBX, useGLTF, useKeyboardControls } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useLocation } from "wouter";
import { useSnapshot } from "valtio";
import { storeState } from "../../stores";
import { useEffect, useRef, useState } from "react";

type GLTFResult = GLTF & {
  nodes: {
    Wolf3D_Hair: THREE.SkinnedMesh;
    Wolf3D_Body: THREE.SkinnedMesh;
    Wolf3D_Outfit_Bottom: THREE.SkinnedMesh;
    Wolf3D_Outfit_Footwear: THREE.SkinnedMesh;
    Wolf3D_Outfit_Top: THREE.SkinnedMesh;
    EyeLeft: THREE.SkinnedMesh;
    EyeRight: THREE.SkinnedMesh;
    Wolf3D_Head: THREE.SkinnedMesh;
    Wolf3D_Teeth: THREE.SkinnedMesh;
    Hips: THREE.Bone;
  };
  materials: {
    Wolf3D_Hair: THREE.MeshStandardMaterial;
    Wolf3D_Body: THREE.MeshStandardMaterial;
    Wolf3D_Outfit_Bottom: THREE.MeshStandardMaterial;
    Wolf3D_Outfit_Footwear: THREE.MeshStandardMaterial;
    Wolf3D_Outfit_Top: THREE.MeshStandardMaterial;
    Wolf3D_Eye: THREE.MeshStandardMaterial;
    Wolf3D_Skin: THREE.MeshStandardMaterial;
    Wolf3D_Teeth: THREE.MeshStandardMaterial;
  };
};

export function Trader(props: JSX.IntrinsicElements["group"]) {
    const group = useRef<THREE.Group>(null);
  const { scene } = useGLTF(
    "/models/shirt_trader/shirt_trader-transformed.glb"
  ) as GLTFResult;
  const [sub] = useKeyboardControls();
  const [, setLocation] = useLocation();
  const { shirt_menu } = useSnapshot(storeState);
  const animations = {
    "Sitting Idle": useFBX("/anims/defaultSitting.fbx").animations[0],
  };

  animations["Sitting Idle"].name = "Sitting Idle";

  const { actions, mixer } = useAnimations(Object.values(animations), group);

  const [currentAnim, setCurrentAnim] =
    useState<keyof typeof animations>("Sitting Idle");

  function handler() {
    setCurrentAnim("Sitting Idle");
  }
  
  useEffect(() => {
    mixer.addEventListener("finished", handler);
    return () => {
      mixer.removeEventListener("finished", handler);
    };
  }, [currentAnim]);

  useEffect(() => {
    return sub(
      (state) => state["show_shirt"],
      (pressed) => {
        if (shirt_menu && pressed) {
          storeState.shirt_menu = false;
          setLocation("/item/03");
        }
      }
    );
  }, [shirt_menu]);

  useEffect(() => {
    if (currentAnim && actions && actions[currentAnim]) {
      if (currentAnim !== "Sitting Idle") {
        actions[currentAnim]!.repetitions = 1;
        actions[currentAnim]!.clampWhenFinished = true;
      }

      actions[currentAnim]!.reset().play();
    }

    return () => {
      actions[currentAnim]?.stop();
    };
  }, [currentAnim, actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={scene} />
      <mesh
          position={[0, 0, 1.1]}
          scale={0.3}
          onPointerEnter={(e) => {
            if (currentAnim !== "Sitting Idle" || e.distance > 4) return;
            storeState.shirt_menu = true;
          }}
          onPointerLeave={() => {
            if (currentAnim !== "Sitting Idle") return;
            storeState.shirt_menu = false;
          }}
        >
          <sphereGeometry args={[1, 1, 2]} />
          <meshBasicMaterial visible={false} />
        </mesh>
    </group>
  );
}



useGLTF.preload("/models/shirt_trader/shirt_trader-transformed.glb");
