/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./Last_island.glb --types 
*/

import * as THREE from "three";
import { useGLTF, useTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { MeshCollider, RigidBody } from "@react-three/rapier";
import { useLayoutEffect } from "react";
import { WaterShader } from "../Water";

type GLTFResult = GLTF & {
  nodes: {
    Landscape_1: THREE.Mesh;
    Landscape_2: THREE.Mesh;
    Landscape_3: THREE.Mesh;
    Landscape_4: THREE.Mesh;
    Icosphere004_1: THREE.Mesh;
    Icosphere004_2: THREE.Mesh;
    Icosphere004_3: THREE.Mesh;
    Cube015_1: THREE.Mesh;
    Cube015_2: THREE.Mesh;
    Cube015_3: THREE.Mesh;
    Cube015_4: THREE.Mesh;
    Cube016_1: THREE.Mesh;
    Cube016_2: THREE.Mesh;
    Cube016_3: THREE.Mesh;
    Cube016_4: THREE.Mesh;
    Cube017_1: THREE.Mesh;
    Cube017_2: THREE.Mesh;
    Cube017_3: THREE.Mesh;
    Cube017_4: THREE.Mesh;
    Cube018_1: THREE.Mesh;
    Cube018_2: THREE.Mesh;
    Cube018_3: THREE.Mesh;
    Cube018_4: THREE.Mesh;
    Cube019_1: THREE.Mesh;
    Cube019_2: THREE.Mesh;
    Cube019_3: THREE.Mesh;
    Cube019_4: THREE.Mesh;
    Cube020_1: THREE.Mesh;
    Cube020_2: THREE.Mesh;
    Cube020_3: THREE.Mesh;
    Cube020_4: THREE.Mesh;
    Cube021_1: THREE.Mesh;
    Cube021_2: THREE.Mesh;
    Cube021_3: THREE.Mesh;
    Cube021_4: THREE.Mesh;
    Cube022_1: THREE.Mesh;
    Cube022_2: THREE.Mesh;
    Cube022_3: THREE.Mesh;
    Cube022_4: THREE.Mesh;
    Cube023_1: THREE.Mesh;
    Cube023_2: THREE.Mesh;
    Cube023_3: THREE.Mesh;
    Cube023_4: THREE.Mesh;
    Cube024_1: THREE.Mesh;
    Cube024_2: THREE.Mesh;
    Cube024_3: THREE.Mesh;
    Cube024_4: THREE.Mesh;
    Cube025_1: THREE.Mesh;
    Cube025_2: THREE.Mesh;
    Cube025_3: THREE.Mesh;
    Cube025_4: THREE.Mesh;
    Cube026_1: THREE.Mesh;
    Cube026_2: THREE.Mesh;
    Cube026_3: THREE.Mesh;
    Cube026_4: THREE.Mesh;
    Cube027_1: THREE.Mesh;
    Cube027_2: THREE.Mesh;
    Cube027_3: THREE.Mesh;
    Cube027_4: THREE.Mesh;
    Cube028_1: THREE.Mesh;
    Cube028_2: THREE.Mesh;
    Cube028_3: THREE.Mesh;
    Cube028_4: THREE.Mesh;
    Cube029_1: THREE.Mesh;
    Cube029_2: THREE.Mesh;
    Cube029_3: THREE.Mesh;
    Cube029_4: THREE.Mesh;
    Cube030_1: THREE.Mesh;
    Cube030_2: THREE.Mesh;
    Cube030_3: THREE.Mesh;
    Cube030_4: THREE.Mesh;
    Cube031_1: THREE.Mesh;
    Cube031_2: THREE.Mesh;
    Cube031_3: THREE.Mesh;
    Cube031_4: THREE.Mesh;
    Cube032_1: THREE.Mesh;
    Cube032_2: THREE.Mesh;
    Cube032_3: THREE.Mesh;
    Cube032_4: THREE.Mesh;
    Cube033_1: THREE.Mesh;
    Cube033_2: THREE.Mesh;
    Cube033_3: THREE.Mesh;
    Cube033_4: THREE.Mesh;
    Cube035_1: THREE.Mesh;
    Cube035_2: THREE.Mesh;
    Cube035_3: THREE.Mesh;
    Cube035_4: THREE.Mesh;
    Icosphere006_1: THREE.Mesh;
    Icosphere006_2: THREE.Mesh;
    Icosphere006_3: THREE.Mesh;
    Icosphere007_1: THREE.Mesh;
    Icosphere007_2: THREE.Mesh;
    Icosphere007_3: THREE.Mesh;
    Icosphere008_1: THREE.Mesh;
    Icosphere008_2: THREE.Mesh;
    Icosphere008_3: THREE.Mesh;
    Icosphere009_1: THREE.Mesh;
    Icosphere009_2: THREE.Mesh;
    Icosphere009_3: THREE.Mesh;
    Icosphere010_1: THREE.Mesh;
    Icosphere010_2: THREE.Mesh;
    Icosphere010_3: THREE.Mesh;
    Icosphere011_1: THREE.Mesh;
    Icosphere011_2: THREE.Mesh;
    Icosphere011_3: THREE.Mesh;
    Icosphere012_1: THREE.Mesh;
    Icosphere012_2: THREE.Mesh;
    Icosphere012_3: THREE.Mesh;
    Icosphere013_1: THREE.Mesh;
    Icosphere013_2: THREE.Mesh;
    Icosphere013_3: THREE.Mesh;
    Icosphere014_1: THREE.Mesh;
    Icosphere014_2: THREE.Mesh;
    Icosphere014_3: THREE.Mesh;
    Icosphere015_1: THREE.Mesh;
    Icosphere015_2: THREE.Mesh;
    Icosphere015_3: THREE.Mesh;
    Icosphere016: THREE.Mesh;
    Icosphere016_1: THREE.Mesh;
    Icosphere016_2: THREE.Mesh;
    Icosphere017_1: THREE.Mesh;
    Icosphere017_2: THREE.Mesh;
    Icosphere017_3: THREE.Mesh;
    Icosphere018: THREE.Mesh;
    Icosphere018_1: THREE.Mesh;
    Icosphere018_2: THREE.Mesh;
    Icosphere019_1: THREE.Mesh;
    Icosphere019_2: THREE.Mesh;
    Icosphere019_3: THREE.Mesh;
    Cube022: THREE.Mesh;
    Cube038_1: THREE.Mesh;
    Cube038_2: THREE.Mesh;
    Torus_1: THREE.Mesh;
    Torus_2: THREE.Mesh;
    Sphere_1: THREE.Mesh;
    Sphere_2: THREE.Mesh;
    Cube039_1: THREE.Mesh;
    Cube039_2: THREE.Mesh;
    Cube040_1: THREE.Mesh;
    Cube040_2: THREE.Mesh;
    Cylinder014: THREE.Mesh;
    Cylinder014_1: THREE.Mesh;
    Cylinder014_2: THREE.Mesh;
    Cube026: THREE.Mesh;
    Plane015: THREE.Mesh;
    Plane015_1: THREE.Mesh;
    Cube027: THREE.Mesh;
    Cube028: THREE.Mesh;
    Plane016: THREE.Mesh;
    Plane016_1: THREE.Mesh;
    Cube029: THREE.Mesh;
    Grid: THREE.Mesh;
    Torus001_1: THREE.Mesh;
    Torus001_2: THREE.Mesh;
    Sphere001_1: THREE.Mesh;
    Sphere001_2: THREE.Mesh;
    Cube030: THREE.Mesh;
    Cube031: THREE.Mesh;
    Cube032: THREE.Mesh;
    Cube033: THREE.Mesh;
    Cube034: THREE.Mesh;
    Cube035: THREE.Mesh;
    Cube036: THREE.Mesh;
    Cube037: THREE.Mesh;
    Cube038: THREE.Mesh;
    Cube039: THREE.Mesh;
    Cube040: THREE.Mesh;
    Cube041: THREE.Mesh;
    Cube042: THREE.Mesh;
    Cube043: THREE.Mesh;
    Cube046: THREE.Mesh;
    Cube047: THREE.Mesh;
    Cube048: THREE.Mesh;
    Cube049: THREE.Mesh;
    Cube050: THREE.Mesh;
    Cube051: THREE.Mesh;
    Cube052: THREE.Mesh;
    Cube054: THREE.Mesh;
    Cube055: THREE.Mesh;
    Cube056: THREE.Mesh;
    Cube057: THREE.Mesh;
    Cube059: THREE.Mesh;
    Cube060: THREE.Mesh;
    Cube062: THREE.Mesh;
    Cube063: THREE.Mesh;
    Cube064: THREE.Mesh;
    Cube065: THREE.Mesh;
    Cube066: THREE.Mesh;
    Cube068: THREE.Mesh;
    Cube069: THREE.Mesh;
    Cube070: THREE.Mesh;
    Cube071: THREE.Mesh;
    Cube072: THREE.Mesh;
    Cube073: THREE.Mesh;
    Cube074: THREE.Mesh;
    Cube075: THREE.Mesh;
    Cube076: THREE.Mesh;
    Cube077: THREE.Mesh;
    Cube078: THREE.Mesh;
    Cube079: THREE.Mesh;
    Cube080: THREE.Mesh;
    Cube081: THREE.Mesh;
    Cube082: THREE.Mesh;
    Cube083: THREE.Mesh;
    Cube084: THREE.Mesh;
    Cube085: THREE.Mesh;
    Cube086: THREE.Mesh;
    Cube087: THREE.Mesh;
    Cube088: THREE.Mesh;
    Cube089: THREE.Mesh;
    Cube090: THREE.Mesh;
    Cube091: THREE.Mesh;
    Cube092: THREE.Mesh;
    Cube093: THREE.Mesh;
    Cube094: THREE.Mesh;
    Cube095: THREE.Mesh;
    Cube096: THREE.Mesh;
    Cube097: THREE.Mesh;
    Cube099: THREE.Mesh;
    Cube100: THREE.Mesh;
    Cube101: THREE.Mesh;
    Cube102: THREE.Mesh;
    Cube103: THREE.Mesh;
    Cube104: THREE.Mesh;
    Cube105: THREE.Mesh;
    Cube106: THREE.Mesh;
    Cube108: THREE.Mesh;
    Cube109: THREE.Mesh;
    Cube110: THREE.Mesh;
    Cube111: THREE.Mesh;
    Cube112: THREE.Mesh;
    Cube114: THREE.Mesh;
    Cube115: THREE.Mesh;
    Cube116: THREE.Mesh;
    Cube117: THREE.Mesh;
    Cube118: THREE.Mesh;
    Cube119: THREE.Mesh;
    Cube120: THREE.Mesh;
    Cube121: THREE.Mesh;
    Cube122: THREE.Mesh;
    Cube124: THREE.Mesh;
    Cube125: THREE.Mesh;
    Cube126: THREE.Mesh;
    Cube130: THREE.Mesh;
    Cube131: THREE.Mesh;
    Cube132: THREE.Mesh;
    Cube133: THREE.Mesh;
    Cube134: THREE.Mesh;
    Cube135: THREE.Mesh;
    Cube136: THREE.Mesh;
    Cube137: THREE.Mesh;
    Cube138: THREE.Mesh;
    Cube139: THREE.Mesh;
    Cube140: THREE.Mesh;
    Cube141: THREE.Mesh;
    Cube142: THREE.Mesh;
    Cube143: THREE.Mesh;
    Cube144: THREE.Mesh;
    Cube145: THREE.Mesh;
    Cube146: THREE.Mesh;
    Cube147: THREE.Mesh;
    Cube148: THREE.Mesh;
    Cube149: THREE.Mesh;
    Cube150: THREE.Mesh;
    Cube151: THREE.Mesh;
    Cube152: THREE.Mesh;
    Cube153: THREE.Mesh;
    Cube154: THREE.Mesh;
    Cube155: THREE.Mesh;
    Cube156: THREE.Mesh;
    Cube157: THREE.Mesh;
    Cube158: THREE.Mesh;
    Cube159: THREE.Mesh;
    Cube162: THREE.Mesh;
    Cube163: THREE.Mesh;
    Cube164: THREE.Mesh;
    Cube165: THREE.Mesh;
    Cube166: THREE.Mesh;
    Cube167: THREE.Mesh;
    Cube168: THREE.Mesh;
    Cube171: THREE.Mesh;
    Cube172: THREE.Mesh;
    Cube177: THREE.Mesh;
    Cube178: THREE.Mesh;
    Cube181: THREE.Mesh;
    Cube182: THREE.Mesh;
    Cube183: THREE.Mesh;
    Cube190: THREE.Mesh;
    Cube191: THREE.Mesh;
    Cube192: THREE.Mesh;
    Cube193: THREE.Mesh;
    Cube194: THREE.Mesh;
    Cube195: THREE.Mesh;
    Cube204: THREE.Mesh;
    Cube205: THREE.Mesh;
    Cube206: THREE.Mesh;
    Cube208: THREE.Mesh;
    Cube209: THREE.Mesh;
    Cube210: THREE.Mesh;
    Cube211: THREE.Mesh;
    Cube213: THREE.Mesh;
    Cube214: THREE.Mesh;
    Cube215: THREE.Mesh;
    Cube216: THREE.Mesh;
    Cube217: THREE.Mesh;
    Cube218: THREE.Mesh;
    Cube221: THREE.Mesh;
    Cube222: THREE.Mesh;
    Cube223: THREE.Mesh;
    Cube224: THREE.Mesh;
    Cube225: THREE.Mesh;
    Cube226: THREE.Mesh;
    Cube227: THREE.Mesh;
    Cube228: THREE.Mesh;
    Cube229: THREE.Mesh;
    Cube230: THREE.Mesh;
    Cube231: THREE.Mesh;
    Cube232: THREE.Mesh;
    Cube233: THREE.Mesh;
    Cube234: THREE.Mesh;
    Cube235: THREE.Mesh;
    Cube236: THREE.Mesh;
    Cube237: THREE.Mesh;
    Cube238: THREE.Mesh;
    Cube239: THREE.Mesh;
    Cube240: THREE.Mesh;
    Cube241: THREE.Mesh;
    Cube242: THREE.Mesh;
    Cube243: THREE.Mesh;
    Cube244: THREE.Mesh;
    Cube245: THREE.Mesh;
    Cube246: THREE.Mesh;
    Cube247: THREE.Mesh;
    Cube248: THREE.Mesh;
    Cube249: THREE.Mesh;
    Cube250: THREE.Mesh;
    Cube251: THREE.Mesh;
    Cube252: THREE.Mesh;
    Cube253: THREE.Mesh;
    Cube254: THREE.Mesh;
    Cylinder017: THREE.Mesh;
    Cylinder017_1: THREE.Mesh;
    Cylinder018: THREE.Mesh;
    Cylinder018_1: THREE.Mesh;
    Cylinder019: THREE.Mesh;
    Cylinder019_1: THREE.Mesh;
    Cylinder020: THREE.Mesh;
    Cylinder020_1: THREE.Mesh;
    Plane002: THREE.Mesh;
    Plane003: THREE.Mesh;
    Plane004: THREE.Mesh;
    Plane005: THREE.Mesh;
    Plane006: THREE.Mesh;
    Plane007: THREE.Mesh;
    Plane008: THREE.Mesh;
    Plane009: THREE.Mesh;
    Plane010: THREE.Mesh;
    Plane011: THREE.Mesh;
    Plane012: THREE.Mesh;
    Plane013: THREE.Mesh;
    Plane014: THREE.Mesh;
  };
  materials: {
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
    ["Material.020"]: THREE.MeshStandardMaterial;
    ["Material.018"]: THREE.MeshStandardMaterial;
    ["Material.019"]: THREE.MeshStandardMaterial;
    ["Material.014"]: THREE.MeshStandardMaterial;
    ["Material.017"]: THREE.MeshStandardMaterial;
    ["Material.015"]: THREE.MeshStandardMaterial;
    ["Material.016"]: THREE.MeshStandardMaterial;
    ["Material.021"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["Material.009"]: THREE.MeshStandardMaterial;
    ["Material.006"]: THREE.MeshStandardMaterial;
    ["Material.007"]: THREE.MeshStandardMaterial;
    ["Material.008"]: THREE.MeshStandardMaterial;
    ["Material.010"]: THREE.MeshStandardMaterial;
    ["Material.011"]: THREE.MeshStandardMaterial;
    ["Material.023"]: THREE.MeshStandardMaterial;
    ["Material.012"]: THREE.MeshStandardMaterial;
    ["Material.022"]: THREE.MeshStandardMaterial;
    ["Material.013"]: THREE.MeshStandardMaterial;
    ["Material.024"]: THREE.MeshStandardMaterial;
    ["Material.025"]: THREE.MeshStandardMaterial;
  };
};

export function Island(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/island/Last_island.glb"
  ) as GLTFResult;

  const [aoMap2048] = useTexture(["/models/island/AOMap_2048_2.png"]);
  useLayoutEffect(() => {
    aoMap2048.flipY = false;
  }, []);

  return (
    <group {...props} dispose={null}>
      <directionalLight
        intensity={0.2}
        color="#ffc7ab"
        position={[0, 1, 20]}
        rotation={[Math.PI / 2, 1, 0]}
      />
      <RigidBody type="fixed" colliders={false}>
        <MeshCollider type="trimesh">
          <group
            position={[0.128, 0.376, -0.272]}
            rotation={[1.661, -1.342, 1.43]}
            scale={[0.018, 0.011, 0.018]}
          >
            <mesh
              geometry={nodes.Icosphere004_1.geometry}
              material={materials["Material.020"]}
            />
            <mesh
              geometry={nodes.Icosphere004_2.geometry}
              material={materials["Material.018"]}
            />
            <mesh
              geometry={nodes.Icosphere004_3.geometry}
              material={materials["Material.019"]}
            />
          </group>
          <group
            position={[-0.339, 0.26, 0.726]}
            rotation={[0, 0, -0.403]}
            scale={[0.002, 0.001, 0.002]}
          >
            <mesh
              geometry={nodes.Icosphere004_1.geometry}
              material={materials["Material.020"]}
            />
            <mesh
              geometry={nodes.Icosphere004_2.geometry}
              material={materials["Material.018"]}
            />
            <mesh
              geometry={nodes.Icosphere004_3.geometry}
              material={materials["Material.019"]}
            />
          </group>
          <group
            position={[0.548, 0.371, -0.26]}
            rotation={[0, 0, -0.403]}
            scale={[0.002, 0.001, 0.002]}
          >
            <mesh
              geometry={nodes.Icosphere004_1.geometry}
              material={materials["Material.020"]}
            />
            <mesh
              geometry={nodes.Icosphere004_2.geometry}
              material={materials["Material.018"]}
            />
            <mesh
              geometry={nodes.Icosphere004_3.geometry}
              material={materials["Material.019"]}
            />
          </group>
          <group
            position={[-0.83, 0.47, -0.073]}
            rotation={[0, 0, -0.403]}
            scale={[0.002, 0.001, 0.002]}
          >
            <mesh
              geometry={nodes.Icosphere004_1.geometry}
              material={materials["Material.020"]}
            />
            <mesh
              geometry={nodes.Icosphere004_2.geometry}
              material={materials["Material.018"]}
            />
            <mesh
              geometry={nodes.Icosphere004_3.geometry}
              material={materials["Material.019"]}
            />
          </group>
          <group
            position={[0.399, 0.234, 1.514]}
            rotation={[0, 0, -0.403]}
            scale={[0.002, 0.001, 0.002]}
          >
            <mesh
              geometry={nodes.Icosphere004_1.geometry}
              material={materials["Material.020"]}
            />
            <mesh
              geometry={nodes.Icosphere004_2.geometry}
              material={materials["Material.018"]}
            />
            <mesh
              geometry={nodes.Icosphere004_3.geometry}
              material={materials["Material.019"]}
            />
          </group>
          <group
            position={[-0.741, 0.139, 1.902]}
            rotation={[-0.301, -0.147, -0.276]}
            scale={[0.019, 0.002, 0.07]}
          >
            <mesh
              geometry={nodes.Cube015_1.geometry}
              material={materials["Material.014"]}
            />
            <mesh
              geometry={nodes.Cube015_2.geometry}
              material={materials["Material.017"]}
            />
            <mesh
              geometry={nodes.Cube015_3.geometry}
              material={materials["Material.015"]}
            />
            <mesh
              geometry={nodes.Cube015_4.geometry}
              material={materials["Material.016"]}
            />
          </group>
          <group
            position={[-0.74, 0.132, 1.9]}
            rotation={[-0.154, -1.027, 0.042]}
            scale={[0.014, 0.002, 0.051]}
          >
            <mesh
              geometry={nodes.Cube016_1.geometry}
              material={materials["Material.014"]}
            />
            <mesh
              geometry={nodes.Cube016_2.geometry}
              material={materials["Material.017"]}
            />
            <mesh
              geometry={nodes.Cube016_3.geometry}
              material={materials["Material.015"]}
            />
            <mesh
              geometry={nodes.Cube016_4.geometry}
              material={materials["Material.016"]}
            />
          </group>
          <group
            position={[-0.783, 0.152, -1.771]}
            rotation={[-2.959, 0.53, 2.481]}
            scale={[0.021, 0.003, 0.078]}
          >
            <mesh
              geometry={nodes.Cube017_1.geometry}
              material={materials["Material.014"]}
            />
            <mesh
              geometry={nodes.Cube017_2.geometry}
              material={materials["Material.017"]}
            />
            <mesh
              geometry={nodes.Cube017_3.geometry}
              material={materials["Material.015"]}
            />
            <mesh
              geometry={nodes.Cube017_4.geometry}
              material={materials["Material.016"]}
            />
          </group>
          <group
            position={[-0.774, 0.139, -1.761]}
            rotation={[-2.797, -0.519, 3.087]}
            scale={[0.015, 0.002, 0.057]}
          >
            <mesh
              geometry={nodes.Cube018_1.geometry}
              material={materials["Material.014"]}
            />
            <mesh
              geometry={nodes.Cube018_2.geometry}
              material={materials["Material.017"]}
            />
            <mesh
              geometry={nodes.Cube018_3.geometry}
              material={materials["Material.015"]}
            />
            <mesh
              geometry={nodes.Cube018_4.geometry}
              material={materials["Material.016"]}
            />
          </group>
          <group
            position={[-1.905, 0.157, 0.511]}
            rotation={[-0.362, 1.113, -0.24]}
            scale={[0.02, 0.003, 0.074]}
          >
            <mesh
              geometry={nodes.Cube019_1.geometry}
              material={materials["Material.014"]}
            />
            <mesh
              geometry={nodes.Cube019_2.geometry}
              material={materials["Material.017"]}
            />
            <mesh
              geometry={nodes.Cube019_3.geometry}
              material={materials["Material.015"]}
            />
            <mesh
              geometry={nodes.Cube019_4.geometry}
              material={materials["Material.016"]}
            />
          </group>
          <group
            position={[-1.914, 0.145, 0.52]}
            rotation={[-2.672, 0.864, 2.543]}
            scale={[0.015, 0.002, 0.054]}
          >
            <mesh
              geometry={nodes.Cube020_1.geometry}
              material={materials["Material.014"]}
            />
            <mesh
              geometry={nodes.Cube020_2.geometry}
              material={materials["Material.017"]}
            />
            <mesh
              geometry={nodes.Cube020_3.geometry}
              material={materials["Material.015"]}
            />
            <mesh
              geometry={nodes.Cube020_4.geometry}
              material={materials["Material.016"]}
            />
          </group>
          <group
            position={[-1.921, 0.145, 0.505]}
            rotation={[-0.666, -0.217, -0.213]}
            scale={[0.01, 0.001, 0.038]}
          >
            <mesh
              geometry={nodes.Cube021_1.geometry}
              material={materials["Material.014"]}
            />
            <mesh
              geometry={nodes.Cube021_2.geometry}
              material={materials["Material.017"]}
            />
            <mesh
              geometry={nodes.Cube021_3.geometry}
              material={materials["Material.015"]}
            />
            <mesh
              geometry={nodes.Cube021_4.geometry}
              material={materials["Material.016"]}
            />
          </group>
          <group
            position={[1.504, 0.201, -1.407]}
            rotation={[-0.362, 1.113, -0.24]}
            scale={[0.02, 0.003, 0.074]}
          >
            <mesh
              geometry={nodes.Cube022_1.geometry}
              material={materials["Material.014"]}
            />
            <mesh
              geometry={nodes.Cube022_2.geometry}
              material={materials["Material.017"]}
            />
            <mesh
              geometry={nodes.Cube022_3.geometry}
              material={materials["Material.015"]}
            />
            <mesh
              geometry={nodes.Cube022_4.geometry}
              material={materials["Material.016"]}
            />
          </group>
          <group
            position={[1.495, 0.188, -1.397]}
            rotation={[-2.672, 0.864, 2.543]}
            scale={[0.015, 0.002, 0.054]}
          >
            <mesh
              geometry={nodes.Cube023_1.geometry}
              material={materials["Material.014"]}
            />
            <mesh
              geometry={nodes.Cube023_2.geometry}
              material={materials["Material.017"]}
            />
            <mesh
              geometry={nodes.Cube023_3.geometry}
              material={materials["Material.015"]}
            />
            <mesh
              geometry={nodes.Cube023_4.geometry}
              material={materials["Material.016"]}
            />
          </group>
          <group
            position={[1.488, 0.188, -1.412]}
            rotation={[-0.666, -0.217, -0.213]}
            scale={[0.01, 0.001, 0.038]}
          >
            <mesh
              geometry={nodes.Cube024_1.geometry}
              material={materials["Material.014"]}
            />
            <mesh
              geometry={nodes.Cube024_2.geometry}
              material={materials["Material.017"]}
            />
            <mesh
              geometry={nodes.Cube024_3.geometry}
              material={materials["Material.015"]}
            />
            <mesh
              geometry={nodes.Cube024_4.geometry}
              material={materials["Material.016"]}
            />
          </group>
          <group
            position={[1.77, 0.165, 1.495]}
            rotation={[-1.124, 1.239, 0.871]}
            scale={[0.019, 0.002, 0.07]}
          >
            <mesh
              geometry={nodes.Cube025_1.geometry}
              material={materials["Material.014"]}
            />
            <mesh
              geometry={nodes.Cube025_2.geometry}
              material={materials["Material.017"]}
            />
            <mesh
              geometry={nodes.Cube025_3.geometry}
              material={materials["Material.015"]}
            />
            <mesh
              geometry={nodes.Cube025_4.geometry}
              material={materials["Material.016"]}
            />
          </group>
          <group
            position={[1.768, 0.159, 1.495]}
            rotation={[-0.093, 0.543, 0.222]}
            scale={[0.014, 0.002, 0.051]}
          >
            <mesh
              geometry={nodes.Cube026_1.geometry}
              material={materials["Material.014"]}
            />
            <mesh
              geometry={nodes.Cube026_2.geometry}
              material={materials["Material.017"]}
            />
            <mesh
              geometry={nodes.Cube026_3.geometry}
              material={materials["Material.015"]}
            />
            <mesh
              geometry={nodes.Cube026_4.geometry}
              material={materials["Material.016"]}
            />
          </group>
          <group
            position={[-0.844, 0.102, -1.555]}
            rotation={[-0.69, -1.322, -1.242]}
            scale={[0.017, 0.002, 0.065]}
          >
            <mesh
              geometry={nodes.Cube027_1.geometry}
              material={materials["Material.014"]}
            />
            <mesh
              geometry={nodes.Cube027_2.geometry}
              material={materials["Material.017"]}
            />
            <mesh
              geometry={nodes.Cube027_3.geometry}
              material={materials["Material.015"]}
            />
            <mesh
              geometry={nodes.Cube027_4.geometry}
              material={materials["Material.016"]}
            />
          </group>
          <group
            position={[-0.843, 0.092, -1.566]}
            rotation={[-0.311, -0.282, -0.32]}
            scale={[0.013, 0.002, 0.047]}
          >
            <mesh
              geometry={nodes.Cube028_1.geometry}
              material={materials["Material.014"]}
            />
            <mesh
              geometry={nodes.Cube028_2.geometry}
              material={materials["Material.017"]}
            />
            <mesh
              geometry={nodes.Cube028_3.geometry}
              material={materials["Material.015"]}
            />
            <mesh
              geometry={nodes.Cube028_4.geometry}
              material={materials["Material.016"]}
            />
          </group>
          <group
            position={[-0.589, 0.167, -1.948]}
            rotation={[-0.668, 1.315, 0.084]}
            scale={[0.015, 0.002, 0.055]}
          >
            <mesh
              geometry={nodes.Cube029_1.geometry}
              material={materials["Material.014"]}
            />
            <mesh
              geometry={nodes.Cube029_2.geometry}
              material={materials["Material.017"]}
            />
            <mesh
              geometry={nodes.Cube029_3.geometry}
              material={materials["Material.015"]}
            />
            <mesh
              geometry={nodes.Cube029_4.geometry}
              material={materials["Material.016"]}
            />
          </group>
          <group
            position={[-0.593, 0.158, -1.94]}
            rotation={[-2.762, 0.655, 2.673]}
            scale={[0.011, 0.001, 0.04]}
          >
            <mesh
              geometry={nodes.Cube030_1.geometry}
              material={materials["Material.014"]}
            />
            <mesh
              geometry={nodes.Cube030_2.geometry}
              material={materials["Material.017"]}
            />
            <mesh
              geometry={nodes.Cube030_3.geometry}
              material={materials["Material.015"]}
            />
            <mesh
              geometry={nodes.Cube030_4.geometry}
              material={materials["Material.016"]}
            />
          </group>
          <group
            position={[-0.975, 0.13, 1.93]}
            rotation={[0.393, 1.314, -0.685]}
            scale={[0.019, 0.002, 0.07]}
          >
            <mesh
              geometry={nodes.Cube031_1.geometry}
              material={materials["Material.014"]}
            />
            <mesh
              geometry={nodes.Cube031_2.geometry}
              material={materials["Material.017"]}
            />
            <mesh
              geometry={nodes.Cube031_3.geometry}
              material={materials["Material.015"]}
            />
            <mesh
              geometry={nodes.Cube031_4.geometry}
              material={materials["Material.016"]}
            />
          </group>
          <group
            position={[-0.979, 0.124, 1.929]}
            rotation={[0.128, 0.437, -0.232]}
            scale={[0.014, 0.002, 0.051]}
          >
            <mesh
              geometry={nodes.Cube032_1.geometry}
              material={materials["Material.014"]}
            />
            <mesh
              geometry={nodes.Cube032_2.geometry}
              material={materials["Material.017"]}
            />
            <mesh
              geometry={nodes.Cube032_3.geometry}
              material={materials["Material.015"]}
            />
            <mesh
              geometry={nodes.Cube032_4.geometry}
              material={materials["Material.016"]}
            />
          </group>
          <group
            position={[1.616, 0.116, 1.872]}
            rotation={[-1.435, 1.269, 1.682]}
            scale={[0.019, 0.002, 0.07]}
          >
            <mesh
              geometry={nodes.Cube033_1.geometry}
              material={materials["Material.014"]}
            />
            <mesh
              geometry={nodes.Cube033_2.geometry}
              material={materials["Material.017"]}
            />
            <mesh
              geometry={nodes.Cube033_3.geometry}
              material={materials["Material.015"]}
            />
            <mesh
              geometry={nodes.Cube033_4.geometry}
              material={materials["Material.016"]}
            />
          </group>
          <group
            position={[-0.454, 0.101, 1.913]}
            rotation={[-0.262, -0.177, -0.498]}
            scale={[0.019, 0.002, 0.07]}
          >
            <mesh
              geometry={nodes.Cube035_1.geometry}
              material={materials["Material.014"]}
            />
            <mesh
              geometry={nodes.Cube035_2.geometry}
              material={materials["Material.017"]}
            />
            <mesh
              geometry={nodes.Cube035_3.geometry}
              material={materials["Material.015"]}
            />
            <mesh
              geometry={nodes.Cube035_4.geometry}
              material={materials["Material.016"]}
            />
          </group>
          <group
            position={[0.615, 0.356, -0.144]}
            rotation={[2.91, 0.16, 2.946]}
            scale={[0.016, 0.01, 0.016]}
          >
            <mesh
              geometry={nodes.Icosphere006_1.geometry}
              material={materials["Material.020"]}
            />
            <mesh
              geometry={nodes.Icosphere006_2.geometry}
              material={materials["Material.018"]}
            />
            <mesh
              geometry={nodes.Icosphere006_3.geometry}
              material={materials["Material.019"]}
            />
          </group>
          <group
            position={[0.074, 0.326, -0.038]}
            rotation={[0.541, 1.116, -0.728]}
            scale={[0.015, 0.009, 0.015]}
          >
            <mesh
              geometry={nodes.Icosphere007_1.geometry}
              material={materials["Material.020"]}
            />
            <mesh
              geometry={nodes.Icosphere007_2.geometry}
              material={materials["Material.018"]}
            />
            <mesh
              geometry={nodes.Icosphere007_3.geometry}
              material={materials["Material.019"]}
            />
          </group>
          <group
            position={[-0.187, 0.298, 0.429]}
            rotation={[2.894, -0.394, 2.812]}
            scale={[0.018, 0.012, 0.018]}
          >
            <mesh
              geometry={nodes.Icosphere008_1.geometry}
              material={materials["Material.020"]}
            />
            <mesh
              geometry={nodes.Icosphere008_2.geometry}
              material={materials["Material.018"]}
            />
            <mesh
              geometry={nodes.Icosphere008_3.geometry}
              material={materials["Material.019"]}
            />
          </group>
          <group
            position={[-0.466, 0.245, 0.872]}
            rotation={[2.666, 1.054, -2.954]}
            scale={[0.015, 0.01, 0.015]}
          >
            <mesh
              geometry={nodes.Icosphere009_1.geometry}
              material={materials["Material.020"]}
            />
            <mesh
              geometry={nodes.Icosphere009_2.geometry}
              material={materials["Material.018"]}
            />
            <mesh
              geometry={nodes.Icosphere009_3.geometry}
              material={materials["Material.019"]}
            />
          </group>
          <group
            position={[-0.293, 0.285, 0.537]}
            rotation={[0.248, -0.403, -0.134]}
            scale={[0.015, 0.01, 0.015]}
          >
            <mesh
              geometry={nodes.Icosphere010_1.geometry}
              material={materials["Material.020"]}
            />
            <mesh
              geometry={nodes.Icosphere010_2.geometry}
              material={materials["Material.018"]}
            />
            <mesh
              geometry={nodes.Icosphere010_3.geometry}
              material={materials["Material.019"]}
            />
          </group>
          <group
            position={[0.315, 0.256, 0.898]}
            rotation={[2.875, -0.535, 2.77]}
            scale={[0.015, 0.009, 0.015]}
          >
            <mesh
              geometry={nodes.Icosphere011_1.geometry}
              material={materials["Material.020"]}
            />
            <mesh
              geometry={nodes.Icosphere011_2.geometry}
              material={materials["Material.018"]}
            />
            <mesh
              geometry={nodes.Icosphere011_3.geometry}
              material={materials["Material.019"]}
            />
          </group>
          <group
            position={[-0.691, 0.38, 0.257]}
            rotation={[0.468, -1.046, 0.18]}
            scale={[0.016, 0.01, 0.016]}
          >
            <mesh
              geometry={nodes.Icosphere012_1.geometry}
              material={materials["Material.020"]}
            />
            <mesh
              geometry={nodes.Icosphere012_2.geometry}
              material={materials["Material.018"]}
            />
            <mesh
              geometry={nodes.Icosphere012_3.geometry}
              material={materials["Material.019"]}
            />
          </group>
          <group
            position={[0.799, 0.391, 0.675]}
            rotation={[2.857, 0.636, 3.081]}
            scale={[0.02, 0.013, 0.02]}
          >
            <mesh
              geometry={nodes.Icosphere013_1.geometry}
              material={materials["Material.020"]}
            />
            <mesh
              geometry={nodes.Icosphere013_2.geometry}
              material={materials["Material.018"]}
            />
            <mesh
              geometry={nodes.Icosphere013_3.geometry}
              material={materials["Material.019"]}
            />
          </group>
          <group
            position={[-0.059, 0.324, -1.108]}
            rotation={[0.653, 1.189, -0.85]}
            scale={[0.02, 0.013, 0.02]}
          >
            <mesh
              geometry={nodes.Icosphere014_1.geometry}
              material={materials["Material.020"]}
            />
            <mesh
              geometry={nodes.Icosphere014_2.geometry}
              material={materials["Material.018"]}
            />
            <mesh
              geometry={nodes.Icosphere014_3.geometry}
              material={materials["Material.019"]}
            />
          </group>
          <group
            position={[0.573, 0.251, -1.538]}
            rotation={[0.25, -0.413, -0.131]}
            scale={[0.018, 0.012, 0.018]}
          >
            <mesh
              geometry={nodes.Icosphere015_1.geometry}
              material={materials["Material.020"]}
            />
            <mesh
              geometry={nodes.Icosphere015_2.geometry}
              material={materials["Material.018"]}
            />
            <mesh
              geometry={nodes.Icosphere015_3.geometry}
              material={materials["Material.019"]}
            />
          </group>
          <group
            position={[0.39, 0.251, -1.675]}
            rotation={[2.909, 0.186, 2.952]}
            scale={[0.018, 0.012, 0.018]}
          >
            <mesh
              geometry={nodes.Icosphere016.geometry}
              material={materials["Material.020"]}
            />
            <mesh
              geometry={nodes.Icosphere016_1.geometry}
              material={materials["Material.018"]}
            />
            <mesh
              geometry={nodes.Icosphere016_2.geometry}
              material={materials["Material.019"]}
            />
          </group>
          <group
            position={[-0.52, 0.471, -0.37]}
            rotation={[0.228, -0.024, -0.227]}
            scale={[0.016, 0.01, 0.016]}
          >
            <mesh
              geometry={nodes.Icosphere017_1.geometry}
              material={materials["Material.020"]}
            />
            <mesh
              geometry={nodes.Icosphere017_2.geometry}
              material={materials["Material.018"]}
            />
            <mesh
              geometry={nodes.Icosphere017_3.geometry}
              material={materials["Material.019"]}
            />
          </group>
          <group
            position={[-0.644, 0.474, -0.243]}
            rotation={[1.038, -1.305, 0.79]}
            scale={[0.016, 0.01, 0.016]}
          >
            <mesh
              geometry={nodes.Icosphere018.geometry}
              material={materials["Material.020"]}
            />
            <mesh
              geometry={nodes.Icosphere018_1.geometry}
              material={materials["Material.018"]}
            />
            <mesh
              geometry={nodes.Icosphere018_2.geometry}
              material={materials["Material.019"]}
            />
          </group>
          <group
            position={[-1.387, 0.354, 0.45]}
            rotation={[0.468, -1.046, 0.18]}
            scale={[0.016, 0.01, 0.016]}
          >
            <mesh
              geometry={nodes.Icosphere019_1.geometry}
              material={materials["Material.020"]}
            />
            <mesh
              geometry={nodes.Icosphere019_2.geometry}
              material={materials["Material.018"]}
            />
            <mesh
              geometry={nodes.Icosphere019_3.geometry}
              material={materials["Material.019"]}
            />
          </group>
          <mesh
            geometry={nodes.Cube022.geometry}
            material={materials["Material.021"]}
            position={[0.055, 0.229, 0.719]}
            rotation={[0, -0.372, 0]}
            scale={[0.063, 0.002, 0.014]}
          />
          <group
            position={[-0.205, 0.088, 1.855]}
            rotation={[-3.062, 1.042, -Math.PI]}
            scale={[0.15, 0.07, 0.07]}
          >
            <mesh
              geometry={nodes.Cube038_1.geometry}
              material={materials["Material.001"]}
            />
            <mesh
              geometry={nodes.Cube038_2.geometry}
              material={materials["Material.016"]}
            />
          </group>
          <group
            position={[0.599, 0.127, 1.992]}
            rotation={[0.251, 0.016, 0.004]}
            scale={0.05}
          >
            <mesh
              geometry={nodes.Torus_1.geometry}
              material={materials["Material.009"]}
            />
            <mesh
              geometry={nodes.Torus_2.geometry}
              material={materials["Material.006"]}
            />
          </group>
          <group
            position={[0.637, 0.186, 1.777]}
            rotation={[0.703, 0.977, 1.197]}
            scale={0.032}
          >
            <mesh
              geometry={nodes.Sphere_1.geometry}
              material={materials["Material.007"]}
            />
            <mesh
              geometry={nodes.Sphere_2.geometry}
              material={materials["Material.006"]}
            />
          </group>
          <group
            position={[0.917, 0.205, 1.879]}
            rotation={[-0.179, 1.196, 0]}
            scale={[0.003, 0.107, 0.032]}
          >
            <mesh
              geometry={nodes.Cube039_1.geometry}
              material={materials["Material.008"]}
            />
            <mesh
              geometry={nodes.Cube039_2.geometry}
              material={materials["Material.006"]}
            />
          </group>
          <group
            position={[0.985, 0.212, 1.91]}
            rotation={[-2.43, 1.402, 2.582]}
            scale={[0.002, 0.097, 0.029]}
          >
            <mesh
              geometry={nodes.Cube040_1.geometry}
              material={materials["Material.007"]}
            />
            <mesh
              geometry={nodes.Cube040_2.geometry}
              material={materials["Material.006"]}
            />
          </group>
          <group
            position={[0.853, 0.197, 1.944]}
            rotation={[-0.251, 0.043, 0]}
            scale={[0.031, 0.112, 0.031]}
          >
            <mesh
              geometry={nodes.Cylinder014.geometry}
              material={materials["Material.010"]}
            />
            <mesh
              geometry={nodes.Cylinder014_1.geometry}
              material={materials["Material.006"]}
            />
            <mesh
              geometry={nodes.Cylinder014_2.geometry}
              material={materials["Material.011"]}
            />
          </group>
          <mesh
            geometry={nodes.Cube026.geometry}
            material={nodes.Cube026.material}
            position={[0.826, 0.159, 1.941]}
            rotation={[2.486, -0.091, 3.124]}
            scale={[0.001, 0.055, 0.002]}
          />
          <group
            position={[0.797, 0.126, 1.992]}
            rotation={[0.676, 0.038, 3.058]}
            scale={[0.031, 0.041, 0.065]}
          >
            <mesh
              geometry={nodes.Plane015.geometry}
              material={materials["Material.009"]}
            />
            <mesh
              geometry={nodes.Plane015_1.geometry}
              material={materials["Material.006"]}
            />
          </group>
          <mesh
            geometry={nodes.Cube027.geometry}
            material={nodes.Cube027.material}
            position={[0.764, 0.161, 1.946]}
            rotation={[2.486, -0.091, 3.124]}
            scale={[0.001, 0.055, 0.002]}
          />
          <mesh
            geometry={nodes.Cube028.geometry}
            material={nodes.Cube028.material}
            position={[0.969, 0.157, 1.983]}
            rotation={[2.167, 0.515, -2.392]}
            scale={[0.001, 0.055, 0.002]}
          />
          <group
            position={[0.906, 0.133, 1.991]}
            rotation={[0.759, -0.767, -2.657]}
            scale={[0.031, 0.041, 0.065]}
          >
            <mesh
              geometry={nodes.Plane016.geometry}
              material={materials["Material.006"]}
            />
            <mesh
              geometry={nodes.Plane016_1.geometry}
              material={materials["Material.023"]}
            />
          </group>
          <mesh
            geometry={nodes.Cube029.geometry}
            material={nodes.Cube029.material}
            position={[0.929, 0.162, 1.935]}
            rotation={[2.167, 0.515, -2.392]}
            scale={[0.001, 0.055, 0.002]}
          />
          {/* Water */}
          {/* <mesh
            geometry={nodes.Grid.geometry}
            material={materials["Material.012"]}
            position={[0, 0.057, 0]}
            rotation={[-Math.PI, 1.529, -Math.PI]}
            scale={16.162}
          /> */}
          <WaterShader
            geom={nodes.Grid.geometry}
            position={[0, 0.057, 0]}
            rotation={[-Math.PI, 1.529, -Math.PI]}
            scale={16.162}
          />
          {/* Water */}
          <group
            position={[-1.355, 0.112, 1.927]}
            rotation={[0.251, 0.016, 0.004]}
            scale={0.05}
          >
            <mesh
              geometry={nodes.Torus001_1.geometry}
              material={materials["Material.009"]}
            />
            <mesh
              geometry={nodes.Torus001_2.geometry}
              material={materials["Material.006"]}
            />
          </group>
          <group
            position={[-1.55, 0.159, 1.472]}
            rotation={[-0.514, -0.468, 1.718]}
            scale={0.032}
          >
            <mesh
              geometry={nodes.Sphere001_1.geometry}
              material={materials["Material.007"]}
            />
            <mesh
              geometry={nodes.Sphere001_2.geometry}
              material={materials["Material.006"]}
            />
          </group>
          <mesh
            geometry={nodes.Cube030.geometry}
            material={materials["Material.022"]}
            position={[-0.755, 0.469, -0.231]}
            rotation={[0, 0, -0.196]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube031.geometry}
            material={materials["Material.022"]}
            position={[-0.352, 0.262, -1.569]}
            rotation={[0, 0, -0.159]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube032.geometry}
            material={materials["Material.022"]}
            position={[-0.295, 0.275, -1.572]}
            rotation={[0, 0, -0.126]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube033.geometry}
            material={materials["Material.022"]}
            position={[-0.33, 0.274, -1.679]}
            rotation={[0, 0, -0.196]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube034.geometry}
            material={materials["Material.022"]}
            position={[-0.282, 0.25, -1.539]}
            rotation={[0, 0, -0.016]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube035.geometry}
            material={materials["Material.022"]}
            position={[-0.279, 0.273, -1.613]}
            rotation={[0, 0, -0.213]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube036.geometry}
            material={materials["Material.022"]}
            position={[-0.251, 0.274, -1.679]}
            rotation={[0, 0, -0.236]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube037.geometry}
            material={materials["Material.022"]}
            position={[0.581, 0.365, -0.204]}
            rotation={[0, 0, -0.212]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube038.geometry}
            material={materials["Material.022"]}
            position={[-0.023, 0.381, -0.268]}
            rotation={[0, 0, -0.312]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube039.geometry}
            material={materials["Material.022"]}
            position={[0.022, 0.386, -0.314]}
            rotation={[0, 0, -0.271]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube040.geometry}
            material={materials["Material.022"]}
            position={[0.036, 0.382, -0.29]}
            rotation={[0, 0, -0.144]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube041.geometry}
            material={materials["Material.022"]}
            position={[0.018, 0.382, -0.281]}
            rotation={[0, 0, -0.164]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube042.geometry}
            material={materials["Material.022"]}
            position={[0.031, 0.281, -1.658]}
            rotation={[0, 0, -0.03]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube043.geometry}
            material={materials["Material.022"]}
            position={[0.092, 0.376, -0.245]}
            rotation={[0, 0, -0.289]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube046.geometry}
            material={materials["Material.022"]}
            position={[0.098, 0.354, -1.212]}
            rotation={[0, 0, -0.082]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube047.geometry}
            material={materials["Material.022"]}
            position={[0.154, 0.353, -1.195]}
            rotation={[0, 0, -0.188]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube048.geometry}
            material={materials["Material.022"]}
            position={[0.146, 0.275, -1.597]}
            rotation={[0, 0, -0.227]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube049.geometry}
            material={materials["Material.022"]}
            position={[0.167, 0.269, -1.627]}
            rotation={[0, 0, -0.201]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube050.geometry}
            material={materials["Material.022"]}
            position={[0.225, 0.376, -0.346]}
            rotation={[0, 0, -0.187]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube051.geometry}
            material={materials["Material.022"]}
            position={[0.156, 0.35, -1.177]}
            rotation={[0, 0, -0.096]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube052.geometry}
            material={materials["Material.022"]}
            position={[0.194, 0.362, -1.248]}
            rotation={[0, 0, -0.137]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube054.geometry}
            material={materials["Material.022"]}
            position={[0.219, 0.36, -1.237]}
            rotation={[0, 0, -0.079]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube055.geometry}
            material={materials["Material.022"]}
            position={[0.43, 0.243, -1.623]}
            rotation={[0, 0, -0.005]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube056.geometry}
            material={materials["Material.022"]}
            position={[0.25, 0.258, -1.654]}
            rotation={[0, 0, -0.208]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube057.geometry}
            material={materials["Material.022"]}
            position={[0.245, 0.226, 0.998]}
            rotation={[0, 0, -0.039]}
            scale={0.007}
          />
          <mesh
            geometry={nodes.Cube059.geometry}
            material={materials["Material.022"]}
            position={[0.277, 0.266, -1.568]}
            rotation={[0, 0, -0.286]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube060.geometry}
            material={materials["Material.022"]}
            position={[0.29, 0.262, 0.884]}
            rotation={[0, 0, -0.176]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube062.geometry}
            material={materials["Material.022"]}
            position={[0.339, 0.253, -1.618]}
            rotation={[0, 0, -0.279]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube063.geometry}
            material={materials["Material.022"]}
            position={[0.385, 0.251, -1.598]}
            rotation={[0, 0, -0.077]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube064.geometry}
            material={materials["Material.022"]}
            position={[0.379, 0.259, -1.541]}
            rotation={[0, 0, -0.279]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube065.geometry}
            material={materials["Material.022"]}
            position={[0.329, 0.25, -1.649]}
            rotation={[0, 0, -0.084]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube066.geometry}
            material={materials["Material.022"]}
            position={[0.36, 0.282, 0.921]}
            rotation={[0, 0, -0.001]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube068.geometry}
            material={materials["Material.022"]}
            position={[-0.735, 0.249, 1.465]}
            rotation={[0, 0, -0.074]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube069.geometry}
            material={materials["Material.022"]}
            position={[-0.074, 0.272, 0.59]}
            rotation={[0, 0, -0.021]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube070.geometry}
            material={materials["Material.022"]}
            position={[-0.654, 0.464, -0.394]}
            rotation={[0, 0, -0.319]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube071.geometry}
            material={materials["Material.022"]}
            position={[-0.69, 0.202, 1.676]}
            rotation={[0, 0, -0.132]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube072.geometry}
            material={materials["Material.022"]}
            position={[-0.78, 0.469, -0.164]}
            rotation={[0, 0, -0.138]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube073.geometry}
            material={materials["Material.022"]}
            position={[-0.631, 0.191, 1.719]}
            rotation={[0, 0, -0.196]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube074.geometry}
            material={materials["Material.022"]}
            position={[-0.644, 0.225, 1.537]}
            rotation={[0, 0, -0.123]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube075.geometry}
            material={materials["Material.022"]}
            position={[-0.589, 0.202, 1.655]}
            rotation={[0, 0, -0.022]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube076.geometry}
            material={materials["Material.022"]}
            position={[-0.675, 0.24, 1.43]}
            rotation={[0, 0, -0.073]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube077.geometry}
            material={materials["Material.022"]}
            position={[-0.673, 0.241, 1.403]}
            rotation={[0, 0, -0.204]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube078.geometry}
            material={materials["Material.022"]}
            position={[-0.541, 0.224, 1.125]}
            rotation={[0, 0, -0.035]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube079.geometry}
            material={materials["Material.022"]}
            position={[-0.612, 0.243, 1.118]}
            rotation={[0, 0, -0.027]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube080.geometry}
            material={materials["Material.022"]}
            position={[-0.606, 0.247, 1.075]}
            rotation={[0, 0, -0.318]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube081.geometry}
            material={materials["Material.022"]}
            position={[-0.647, 0.467, -0.364]}
            rotation={[0, 0, -0.035]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube082.geometry}
            material={materials["Material.022"]}
            position={[-0.459, 0.22, 1.013]}
            rotation={[0, 0, -0.043]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube083.geometry}
            material={materials["Material.022"]}
            position={[-0.364, 0.233, 0.846]}
            rotation={[0, 0, -0.112]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube084.geometry}
            material={materials["Material.022"]}
            position={[-0.386, 0.26, 0.756]}
            rotation={[0, 0, -0.13]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube085.geometry}
            material={materials["Material.022"]}
            position={[-0.338, 0.269, -1.596]}
            rotation={[0, 0, -0.019]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube086.geometry}
            material={materials["Material.022"]}
            position={[-0.349, 0.258, 0.74]}
            rotation={[0, 0, -0.085]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube087.geometry}
            material={materials["Material.022"]}
            position={[-0.358, 0.272, 0.685]}
            rotation={[0, 0, -0.197]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube088.geometry}
            material={materials["Material.022"]}
            position={[-0.303, 0.268, 0.665]}
            rotation={[0, 0, -0.152]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube089.geometry}
            material={materials["Material.022"]}
            position={[-0.238, 0.282, 0.567]}
            rotation={[0, 0, -0.272]}
            scale={0.007}
          />
          <mesh
            geometry={nodes.Cube090.geometry}
            material={materials["Material.022"]}
            position={[-0.291, 0.276, -1.562]}
            rotation={[0, 0, -0.27]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube091.geometry}
            material={materials["Material.022"]}
            position={[-0.273, 0.274, -1.673]}
            rotation={[0, 0, -0.124]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube092.geometry}
            material={materials["Material.022"]}
            position={[-0.437, 0.258, 0.809]}
            rotation={[0, 0, -0.261]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube093.geometry}
            material={materials["Material.022"]}
            position={[-0.316, 0.274, 0.646]}
            rotation={[0, 0, -0.053]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube094.geometry}
            material={materials["Material.022"]}
            position={[-0.046, 0.312, 0.398]}
            rotation={[0, 0, -0.083]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube095.geometry}
            material={materials["Material.022"]}
            position={[-0.042, 0.319, 0.361]}
            rotation={[0, 0, -0.176]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube096.geometry}
            material={materials["Material.022"]}
            position={[-0.23, 0.289, -1.603]}
            rotation={[0, 0, -0.02]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube097.geometry}
            material={materials["Material.022"]}
            position={[-0.098, 0.286, 0.529]}
            rotation={[0, 0, -0.315]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube099.geometry}
            material={materials["Material.022"]}
            position={[0.106, 0.316, 0.388]}
            rotation={[0, 0, -0.256]}
            scale={0.007}
          />
          <mesh
            geometry={nodes.Cube100.geometry}
            material={materials["Material.022"]}
            position={[-0.021, 0.296, 0.488]}
            rotation={[0, 0, -0.302]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube101.geometry}
            material={materials["Material.022"]}
            position={[0.016, 0.268, 0.616]}
            rotation={[0, 0, -0.037]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube102.geometry}
            material={materials["Material.022"]}
            position={[0.043, 0.324, 0.331]}
            rotation={[0, 0, -0.176]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube103.geometry}
            material={materials["Material.022"]}
            position={[0.009, 0.317, 0.375]}
            rotation={[0, 0, -0.05]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube104.geometry}
            material={materials["Material.022"]}
            position={[-0.047, 0.343, 0.225]}
            rotation={[0, 0, -0.284]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube105.geometry}
            material={materials["Material.022"]}
            position={[-0.033, 0.38, -0.259]}
            rotation={[0, 0, -0.311]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube106.geometry}
            material={materials["Material.022"]}
            position={[0.255, 0.238, 0.941]}
            rotation={[0, 0, -0.117]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube108.geometry}
            material={materials["Material.022"]}
            position={[0.005, 0.381, -0.273]}
            rotation={[0, 0, -0.052]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube109.geometry}
            material={materials["Material.022"]}
            position={[0.007, 0.389, -0.333]}
            rotation={[0, 0, -0.272]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube110.geometry}
            material={materials["Material.022"]}
            position={[-0.023, 0.337, -1.148]}
            rotation={[0, 0, -0.012]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube111.geometry}
            material={materials["Material.022"]}
            position={[0.004, 0.356, -1.237]}
            rotation={[0, 0, -0.148]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube112.geometry}
            material={materials["Material.022"]}
            position={[-0.069, 0.311, 0.403]}
            rotation={[0, 0, -0.188]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube114.geometry}
            material={materials["Material.022"]}
            position={[0.056, 0.386, -0.33]}
            rotation={[0, 0, -0.137]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube115.geometry}
            material={materials["Material.022"]}
            position={[0.044, 0.398, -0.378]}
            rotation={[0, 0, -0.16]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube116.geometry}
            material={materials["Material.022"]}
            position={[0.302, 0.219, 1.161]}
            rotation={[0.015, -0.118, 0.168]}
            scale={0.007}
          />
          <mesh
            geometry={nodes.Cube117.geometry}
            material={materials["Material.022"]}
            position={[0.064, 0.385, -0.331]}
            rotation={[0, 0, -0.199]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube118.geometry}
            material={materials["Material.022"]}
            position={[0.074, 0.389, -0.383]}
            rotation={[0, 0, -0.256]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube119.geometry}
            material={materials["Material.022"]}
            position={[0.135, 0.268, 0.674]}
            rotation={[0, 0, -0.033]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube120.geometry}
            material={materials["Material.022"]}
            position={[0.153, 0.374, -0.253]}
            rotation={[0, 0, -0.076]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube121.geometry}
            material={materials["Material.022"]}
            position={[0.238, 0.21, 1.17]}
            rotation={[0, 0, -0.297]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube122.geometry}
            material={materials["Material.022"]}
            position={[0.338, 0.233, 1.197]}
            rotation={[0, 0, -0.037]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube124.geometry}
            material={materials["Material.022"]}
            position={[0.176, 0.372, -0.231]}
            rotation={[0, 0, -0.006]}
            scale={0.007}
          />
          <mesh
            geometry={nodes.Cube125.geometry}
            material={materials["Material.022"]}
            position={[0.204, 0.279, 0.677]}
            rotation={[0, 0, -0.106]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube126.geometry}
            material={materials["Material.022"]}
            position={[0.264, 0.326, 0.345]}
            rotation={[0, 0, -0.139]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube130.geometry}
            material={materials["Material.022"]}
            position={[0.226, 0.373, -0.275]}
            rotation={[0, 0, -0.05]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube131.geometry}
            material={materials["Material.022"]}
            position={[0.2, 0.376, -0.304]}
            rotation={[0, 0, -0.179]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube132.geometry}
            material={materials["Material.022"]}
            position={[0.214, 0.274, -1.558]}
            rotation={[0, 0, -0.315]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube133.geometry}
            material={materials["Material.022"]}
            position={[0.28, 0.231, 1.149]}
            rotation={[0.015, -0.118, -0.076]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube134.geometry}
            material={materials["Material.022"]}
            position={[0.371, 0.226, 1.207]}
            rotation={[0, 0, -0.019]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube135.geometry}
            material={materials["Material.022"]}
            position={[0.236, 0.279, 0.715]}
            rotation={[0, 0, -0.089]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube136.geometry}
            material={materials["Material.022"]}
            position={[0.261, 0.32, 0.394]}
            rotation={[0, 0, -0.016]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube137.geometry}
            material={materials["Material.022"]}
            position={[0.242, 0.266, -1.6]}
            rotation={[0, 0, -0.289]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube138.geometry}
            material={materials["Material.022"]}
            position={[0.213, 0.262, -1.648]}
            rotation={[0, 0, -0.109]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube139.geometry}
            material={materials["Material.022"]}
            position={[0.274, 0.234, 1.015]}
            rotation={[0, 0, -0.05]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube140.geometry}
            material={materials["Material.022"]}
            position={[0.302, 0.24, 1.038]}
            rotation={[0, 0, -0.223]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube141.geometry}
            material={materials["Material.022"]}
            position={[0.295, 0.281, 0.804]}
            rotation={[0, 0, -0.033]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube142.geometry}
            material={materials["Material.022"]}
            position={[0.283, 0.273, 0.822]}
            rotation={[0, 0, -0.073]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube143.geometry}
            material={materials["Material.022"]}
            position={[0.259, 0.256, -1.654]}
            rotation={[0, 0, -0.111]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube144.geometry}
            material={materials["Material.022"]}
            position={[0.325, 0.274, 0.882]}
            rotation={[0, 0, -0.141]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube145.geometry}
            material={materials["Material.022"]}
            position={[0.28, 0.312, 0.453]}
            rotation={[0, 0, -0.138]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube146.geometry}
            material={materials["Material.022"]}
            position={[0.302, 0.318, 0.427]}
            rotation={[0, 0, -0.217]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube147.geometry}
            material={materials["Material.022"]}
            position={[0.395, 0.333, 0.337]}
            rotation={[0, 0, -0.308]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube148.geometry}
            material={materials["Material.022"]}
            position={[0.33, 0.334, 0.293]}
            rotation={[0, 0, -0.134]}
            scale={0.007}
          />
          <mesh
            geometry={nodes.Cube149.geometry}
            material={materials["Material.022"]}
            position={[0.417, 0.344, 0.2]}
            rotation={[0, 0, -0.019]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube150.geometry}
            material={materials["Material.022"]}
            position={[0.392, 0.258, -1.535]}
            rotation={[0, 0, -0.237]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube151.geometry}
            material={materials["Material.022"]}
            position={[0.354, 0.248, -1.638]}
            rotation={[0, 0, -0.135]}
            scale={0.007}
          />
          <mesh
            geometry={nodes.Cube152.geometry}
            material={materials["Material.022"]}
            position={[0.336, 0.245, -1.676]}
            rotation={[0, 0, -0.024]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube153.geometry}
            material={materials["Material.022"]}
            position={[0.363, 0.235, -1.706]}
            rotation={[0, 0, -0.041]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube154.geometry}
            material={materials["Material.022"]}
            position={[0.318, 0.208, 1.649]}
            rotation={[0, 0, -0.222]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube155.geometry}
            material={materials["Material.022"]}
            position={[0.421, 0.343, 0.215]}
            rotation={[0, 0, -0.016]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube156.geometry}
            material={materials["Material.022"]}
            position={[0.367, 0.34, 0.28]}
            rotation={[0, 0, -0.18]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube157.geometry}
            material={materials["Material.022"]}
            position={[0.406, 0.34, 0.247]}
            rotation={[0, 0, -0.073]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube158.geometry}
            material={materials["Material.022"]}
            position={[0.4, 0.256, -1.549]}
            rotation={[0, 0, -0.262]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube159.geometry}
            material={materials["Material.022"]}
            position={[0.385, 0.273, 1.02]}
            rotation={[0, 0, -0.118]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube162.geometry}
            material={materials["Material.022"]}
            position={[0.422, 0.249, -1.578]}
            rotation={[0, 0, -0.25]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube163.geometry}
            material={materials["Material.022"]}
            position={[0.439, 0.24, -1.636]}
            rotation={[0, 0, -0.143]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube164.geometry}
            material={materials["Material.022"]}
            position={[0.422, 0.239, -1.652]}
            rotation={[0, 0, -0.063]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube165.geometry}
            material={materials["Material.022"]}
            position={[0.35, 0.214, 1.62]}
            rotation={[0, 0, -0.096]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube166.geometry}
            material={materials["Material.022"]}
            position={[0.407, 0.214, 1.639]}
            rotation={[0, 0, -0.202]}
            scale={0.007}
          />
          <mesh
            geometry={nodes.Cube167.geometry}
            material={materials["Material.022"]}
            position={[0.575, 0.256, -1.457]}
            rotation={[0, 0, -0.293]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube168.geometry}
            material={materials["Material.022"]}
            position={[0.376, 0.336, 0.307]}
            rotation={[0, 0, -0.275]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube171.geometry}
            material={materials["Material.022"]}
            position={[0.308, 0.221, 1.292]}
            rotation={[0, 0, -0.033]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube172.geometry}
            material={materials["Material.022"]}
            position={[0.412, 0.253, 1.126]}
            rotation={[0, 0, -0.206]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube177.geometry}
            material={materials["Material.022"]}
            position={[0.586, 0.371, -0.26]}
            rotation={[0, 0, -0.2]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube178.geometry}
            material={materials["Material.022"]}
            position={[0.421, 0.236, 1.569]}
            rotation={[0, 0, -0.031]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube181.geometry}
            material={materials["Material.022"]}
            position={[0.396, 0.24, 1.336]}
            rotation={[0, 0, -0.303]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube182.geometry}
            material={materials["Material.022"]}
            position={[0.319, 0.221, 1.544]}
            rotation={[0, 0, -0.039]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube183.geometry}
            material={materials["Material.022"]}
            position={[0.459, 0.245, 1.497]}
            rotation={[0, 0, -0.134]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube190.geometry}
            material={materials["Material.022"]}
            position={[0.337, 0.234, 1.377]}
            rotation={[-0.03, -0.039, -0.161]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube191.geometry}
            material={materials["Material.022"]}
            position={[0.348, 0.327, 0.373]}
            rotation={[0, 0, -0.095]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube192.geometry}
            material={materials["Material.022"]}
            position={[0.351, 0.266, 0.963]}
            rotation={[0, 0, -0.23]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube193.geometry}
            material={materials["Material.022"]}
            position={[0.311, 0.256, 0.951]}
            rotation={[0, 0, -0.264]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube194.geometry}
            material={materials["Material.022"]}
            position={[0.256, 0.221, 1.096]}
            rotation={[0, 0, -0.198]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube195.geometry}
            material={materials["Material.022"]}
            position={[0.464, 0.235, 1.541]}
            rotation={[0, 0, -0.067]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube204.geometry}
            material={materials["Material.022"]}
            position={[0.393, 0.26, 1.087]}
            rotation={[0, 0, -0.041]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube205.geometry}
            material={materials["Material.022"]}
            position={[0.351, 0.249, 1.082]}
            rotation={[0, 0, -0.306]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube206.geometry}
            material={materials["Material.022"]}
            position={[0.262, 0.213, 1.562]}
            rotation={[0, 0, -0.11]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube208.geometry}
            material={materials["Material.022"]}
            position={[0.027, 0.303, 0.453]}
            rotation={[0, 0, -0.182]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube209.geometry}
            material={materials["Material.022"]}
            position={[0.026, 0.31, 0.416]}
            rotation={[0, 0, -0.192]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube210.geometry}
            material={materials["Material.022"]}
            position={[0.081, 0.305, 0.455]}
            rotation={[0, 0, -0.239]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube211.geometry}
            material={materials["Material.022"]}
            position={[0.309, 0.235, 1.097]}
            rotation={[0, 0, -0.279]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube213.geometry}
            material={materials["Material.022"]}
            position={[-0.061, 0.351, 0.187]}
            rotation={[0, 0, -0.266]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube214.geometry}
            material={materials["Material.022"]}
            position={[0.366, 0.25, 1.107]}
            rotation={[0, 0, -0.263]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube215.geometry}
            material={materials["Material.022"]}
            position={[0.228, 0.307, 0.486]}
            rotation={[0, 0, -0.253]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube216.geometry}
            material={materials["Material.022"]}
            position={[0.038, 0.326, 0.319]}
            rotation={[0, 0, -0.307]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube217.geometry}
            material={materials["Material.022"]}
            position={[-0.101, 0.357, 0.178]}
            rotation={[0, 0, -0.258]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube218.geometry}
            material={materials["Material.022"]}
            position={[0.067, 0.291, 0.529]}
            rotation={[0, 0, -0.073]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube221.geometry}
            material={materials["Material.022"]}
            position={[-0.038, 0.387, -0.317]}
            rotation={[0, 0, -0.162]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube222.geometry}
            material={materials["Material.022"]}
            position={[0.006, 0.295, 0.493]}
            rotation={[0, 0, -0.047]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube223.geometry}
            material={materials["Material.022"]}
            position={[-0.202, 0.263, 0.644]}
            rotation={[0, 0, -0.115]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube224.geometry}
            material={materials["Material.022"]}
            position={[-0.448, 0.249, 0.86]}
            rotation={[0, 0, -0.116]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube225.geometry}
            material={materials["Material.022"]}
            position={[0.02, 0.31, 0.413]}
            rotation={[0, 0, -0.304]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube226.geometry}
            material={materials["Material.022"]}
            position={[-0.347, 0.248, 0.779]}
            rotation={[0, 0, -0.047]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube227.geometry}
            material={materials["Material.022"]}
            position={[-0.611, 0.473, -0.277]}
            rotation={[0, 0, -0.041]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube228.geometry}
            material={materials["Material.022"]}
            position={[-0.573, 0.472, -0.333]}
            rotation={[0, 0, -0.046]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube229.geometry}
            material={materials["Material.022"]}
            position={[-0.569, 0.181, 1.781]}
            rotation={[0, 0, -0.244]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube230.geometry}
            material={materials["Material.022"]}
            position={[-0.7, 0.469, -0.273]}
            rotation={[0, 0, -0.201]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube231.geometry}
            material={materials["Material.022"]}
            position={[-0.641, 0.472, -0.269]}
            rotation={[0, 0, -0.28]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube232.geometry}
            material={materials["Material.022"]}
            position={[-0.6, 0.179, 1.806]}
            rotation={[0, 0, -0.036]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube233.geometry}
            material={materials["Material.022"]}
            position={[-0.604, 0.237, 1.152]}
            rotation={[0, 0, -0.138]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube234.geometry}
            material={materials["Material.022"]}
            position={[-0.632, 0.231, 1.297]}
            rotation={[0, 0, -0.084]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube235.geometry}
            material={materials["Material.022"]}
            position={[-0.695, 0.474, -0.186]}
            rotation={[0, 0, -0.273]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube236.geometry}
            material={materials["Material.022"]}
            position={[-0.659, 0.243, 1.212]}
            rotation={[0, 0, -0.266]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube237.geometry}
            material={materials["Material.022"]}
            position={[-0.827, 0.474, -0.016]}
            rotation={[0, 0, -0.189]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube238.geometry}
            material={materials["Material.022"]}
            position={[0.227, 0.287, 0.645]}
            rotation={[0, 0, -0.021]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube239.geometry}
            material={materials["Material.022"]}
            position={[0.399, 0.192, 1.789]}
            rotation={[0, 0, -0.195]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube240.geometry}
            material={materials["Material.022"]}
            position={[0.401, 0.238, 1.449]}
            rotation={[0, 0, -0.012]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube241.geometry}
            material={materials["Material.022"]}
            position={[0.314, 0.194, 1.741]}
            rotation={[0, 0, -0.146]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube242.geometry}
            material={materials["Material.022"]}
            position={[0.334, 0.187, 1.782]}
            rotation={[0, 0, -0.295]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube243.geometry}
            material={materials["Material.022"]}
            position={[0.261, 0.195, 1.748]}
            rotation={[0, 0, -0.159]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube244.geometry}
            material={materials["Material.022"]}
            position={[0.341, 0.199, 1.71]}
            rotation={[0, 0, -0.036]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube245.geometry}
            material={materials["Material.022"]}
            position={[0.376, 0.201, 1.697]}
            rotation={[0, 0, -0.153]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube246.geometry}
            material={materials["Material.022"]}
            position={[0.34, 0.187, 1.78]}
            rotation={[0, 0, -0.262]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube247.geometry}
            material={materials["Material.022"]}
            position={[0.443, 0.218, 1.639]}
            rotation={[0, 0, -0.283]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube248.geometry}
            material={materials["Material.022"]}
            position={[0.399, 0.234, 1.514]}
            rotation={[0, 0, -0.079]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube249.geometry}
            material={materials["Material.022"]}
            position={[0.345, 0.229, 1.449]}
            rotation={[0, 0, -0.059]}
            scale={0.009}
          />
          <mesh
            geometry={nodes.Cube250.geometry}
            material={materials["Material.022"]}
            position={[0.324, 0.231, 1.18]}
            rotation={[0, 0, -0.04]}
            scale={0.008}
          />
          <mesh
            geometry={nodes.Cube251.geometry}
            material={materials["Material.022"]}
            position={[0.369, 0.237, 1.284]}
            rotation={[-0.069, -0.094, -0.197]}
            scale={0.011}
          />
          <mesh
            geometry={nodes.Cube252.geometry}
            material={materials["Material.022"]}
            position={[0.411, 0.232, 1.401]}
            rotation={[0, 0, -0.177]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube253.geometry}
            material={materials["Material.022"]}
            position={[0.314, 0.181, 1.833]}
            rotation={[0, 0, -0.189]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Cube254.geometry}
            material={materials["Material.022"]}
            position={[0.274, 0.216, 1.482]}
            rotation={[0, 0, -0.239]}
            scale={0.008}
          />
          <group
            position={[-0.085, 0.095, 0.961]}
            rotation={[2.178, 0.038, 1.135]}
            scale={[0.024, 0.032, 0.024]}
          >
            <mesh
              geometry={nodes.Cylinder017.geometry}
              material={materials["Material.013"]}
            />
            <mesh
              geometry={nodes.Cylinder017_1.geometry}
              material={materials["Material.024"]}
            />
          </group>
          <group
            position={[-0.168, 0.155, 0.748]}
            rotation={[2.81, 0.492, 0.111]}
            scale={[0.024, 0.032, 0.024]}
          >
            <mesh
              geometry={nodes.Cylinder018.geometry}
              material={materials["Material.013"]}
            />
            <mesh
              geometry={nodes.Cylinder018_1.geometry}
              material={materials["Material.024"]}
            />
          </group>
          <group
            position={[-0.648, 0.115, 2.126]}
            rotation={[1.706, 0.766, 0.661]}
            scale={[0.024, 0.032, 0.024]}
          >
            <mesh
              geometry={nodes.Cylinder019.geometry}
              material={materials["Material.013"]}
            />
            <mesh
              geometry={nodes.Cylinder019_1.geometry}
              material={materials["Material.024"]}
            />
          </group>
          <group
            position={[-0.953, 0.162, 1.809]}
            rotation={[-0.892, 1.03, 3.063]}
            scale={[0.024, 0.032, 0.024]}
          >
            <mesh
              geometry={nodes.Cylinder020.geometry}
              material={materials["Material.013"]}
            />
            <mesh
              geometry={nodes.Cylinder020_1.geometry}
              material={materials["Material.024"]}
            />
          </group>
          <mesh
            geometry={nodes.Plane002.geometry}
            material={materials["Material.025"]}
            position={[-2.385, -0.197, 4.081]}
            scale={1.694}
          />
          <mesh
            geometry={nodes.Plane003.geometry}
            material={materials["Material.025"]}
            position={[1.629, -0.203, -4.948]}
            rotation={[Math.PI, -1.444, Math.PI]}
            scale={[1.718, 1.694, 2.826]}
          />
          <mesh
            geometry={nodes.Plane004.geometry}
            material={materials["Material.025"]}
            position={[-4.201, -0.172, -3.401]}
            rotation={[Math.PI, -0.51, Math.PI]}
            scale={[1.718, 1.694, 2.826]}
          />
          <mesh
            geometry={nodes.Plane005.geometry}
            material={materials["Material.025"]}
            position={[5.416, -0.14, 3.336]}
            rotation={[0, -1.416, 0]}
            scale={[1.274, 1.256, 2.095]}
          />
          <mesh
            geometry={nodes.Plane006.geometry}
            material={materials["Material.025"]}
            position={[2.658, -0.069, -3.504]}
            rotation={[-2.749, -1.055, -2.937]}
            scale={[0.647, 0.638, 1.064]}
          />
          <mesh
            geometry={nodes.Plane007.geometry}
            material={materials["Material.025"]}
            position={[-1.126, -0.069, -5.308]}
            rotation={[0.126, -0.94, -0.092]}
            scale={[0.647, 0.638, 1.064]}
          />
          <mesh
            geometry={nodes.Plane008.geometry}
            material={materials["Material.025"]}
            position={[-1.025, 0.239, 0.594]}
            rotation={[0.26, -0.964, 0.049]}
            scale={[0.526, 0.305, 0.493]}
          />
          <mesh
            geometry={nodes.Plane009.geometry}
            material={materials["Material.025"]}
            position={[-1.028, 0.117, 1.892]}
            scale={0.075}
          />
          <mesh
            geometry={nodes.Plane010.geometry}
            material={materials["Material.025"]}
            position={[-1.51, 0.117, 1.592]}
            rotation={[0, 1.006, 0]}
            scale={[0.105, 0.057, 0.105]}
          />
          <mesh
            geometry={nodes.Plane011.geometry}
            material={materials["Material.025"]}
            position={[-1.801, 0.104, 1.224]}
            rotation={[Math.PI, -1.315, Math.PI]}
            scale={[0.105, 0.057, 0.105]}
          />
          <mesh
            geometry={nodes.Plane012.geometry}
            material={materials["Material.025"]}
            position={[0.611, 0.133, 1.873]}
            scale={[0.075, 0.063, 0.075]}
          />
          <mesh
            geometry={nodes.Plane013.geometry}
            material={materials["Material.025"]}
            position={[0.177, 0.071, 2.112]}
            rotation={[Math.PI, -0.414, Math.PI]}
            scale={[0.075, 0.063, 0.075]}
          />
          <mesh
            geometry={nodes.Plane014.geometry}
            material={materials["Material.025"]}
            position={[1.321, 0.104, 1.942]}
            scale={[0.197, 0.074, 0.197]}
          />
          {/* Landscape */}
          <mesh geometry={nodes.Landscape_1.geometry}>
            <meshStandardMaterial
              {...materials["Material.002"]}
              aoMap={aoMap2048}
            />
          </mesh>
          <mesh
            geometry={nodes.Landscape_2.geometry}
            material={materials["Material.003"]}
          >
            <meshStandardMaterial
              {...materials["Material.003"]}
              aoMap={aoMap2048}
            />
          </mesh>
          <mesh
            geometry={nodes.Landscape_3.geometry}
            material={materials["Material.004"]}
          >
            <meshStandardMaterial
              {...materials["Material.004"]}
              aoMap={aoMap2048}
            />
          </mesh>
          <mesh
            geometry={nodes.Landscape_4.geometry}
            material={materials["Material.005"]}
          >
            {/* <meshStandardMaterial
              {...materials["Material.005"]}
              aoMap={aoMap2048}
            /> */}
          </mesh>
        </MeshCollider>
      </RigidBody>
    </group>
  );
}

useGLTF.preload("/models/island/Last_island.glb");
