/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ./coffee_3.glb --types 
*/

import * as THREE from "three";
import React, { ReactNode } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { RigidBody } from "@react-three/rapier";

type GLTFResult = GLTF & {
  nodes: {
    Office2_Books1: THREE.Mesh;
    Office2_Books10: THREE.Mesh;
    Office2_Books11: THREE.Mesh;
    Office2_Books12: THREE.Mesh;
    Office2_Books13: THREE.Mesh;
    Office2_Books14: THREE.Mesh;
    Office2_Books15: THREE.Mesh;
    Office2_Books16: THREE.Mesh;
    Office2_Books2: THREE.Mesh;
    Office2_Books3: THREE.Mesh;
    Office2_Books4: THREE.Mesh;
    Office2_Books5: THREE.Mesh;
    Office2_Books6: THREE.Mesh;
    Office2_Books7: THREE.Mesh;
    Office2_Books8: THREE.Mesh;
    Office2_Books9: THREE.Mesh;
    Office2_box_1: THREE.Mesh;
    Office2_box_2: THREE.Mesh;
    Office2_box_3: THREE.Mesh;
    Office2_box_4: THREE.Mesh;
    Office2_box_5: THREE.Mesh;
    Office2_box_6: THREE.Mesh;
    Office2_box_7: THREE.Mesh;
    Office2_carpet: THREE.Mesh;
    Office2_chair: THREE.Mesh;
    Office2_clock_1: THREE.Mesh;
    Office2_decoration1: THREE.Mesh;
    Office2_decoration2: THREE.Mesh;
    Office2_Flower: THREE.Mesh;
    Office2_Keyboard: THREE.Mesh;
    Office2_little_table: THREE.Mesh;
    Office2_magazines1: THREE.Mesh;
    Office2_magazines2: THREE.Mesh;
    Office2_magazines3: THREE.Mesh;
    Office2_magazines4: THREE.Mesh;
    Office2_magazines5: THREE.Mesh;
    Office2_monitor1: THREE.Mesh;
    Office2_Mouse: THREE.Mesh;
    Office2_parquet1: THREE.Mesh;
    Office2_parquet2: THREE.Mesh;
    Office2_parquet2001: THREE.Mesh;
    Office2_parquet2002: THREE.Mesh;
    Office2_Pens: THREE.Mesh;
    Office2_Photoframe1: THREE.Mesh;
    Office2_Photoframe_2: THREE.Mesh;
    Office2_Photoframe_3: THREE.Mesh;
    Office2_Photoframe_4: THREE.Mesh;
    Office2_picture: THREE.Mesh;
    Office2_Room_Paper: THREE.Mesh;
    Office2_shelves: THREE.Mesh;
    Office2_sofa: THREE.Mesh;
    Office2_stand: THREE.Mesh;
    Office2_table: THREE.Mesh;
    Office2_vial_1: THREE.Mesh;
    Office2_vial_2: THREE.Mesh;
    Office2_Vinyl_players: THREE.Mesh;
    Office2_Vinyls: THREE.Mesh;
    Plane002_1: THREE.Mesh;
    Plane002_2: THREE.Mesh;
    Plane004: THREE.Mesh;
    Plane005: THREE.Mesh;
    Plane006: THREE.Mesh;
    Plane007: THREE.Mesh;
    Left_Window: THREE.Mesh;
    Right_Window_: THREE.Mesh;
    Plane008: THREE.Mesh;
    Plane009: THREE.Mesh;
    Plane010: THREE.Mesh;
    Plane003: THREE.Mesh;
    Text: THREE.Mesh;
    Text006: THREE.Mesh;
    Plane011: THREE.Mesh;
    Text001: THREE.Mesh;
    Text007: THREE.Mesh;
    Plane012: THREE.Mesh;
    Text002: THREE.Mesh;
    Text008: THREE.Mesh;
    Plane013: THREE.Mesh;
    Text003: THREE.Mesh;
    Plane014: THREE.Mesh;
    Text004: THREE.Mesh;
    Circle002_1: THREE.Mesh;
    Circle002_2: THREE.Mesh;
    Plane: THREE.Mesh;
  };
  materials: {
    LP_Rooms: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.009"]: THREE.MeshStandardMaterial;
    ["Material.006"]: THREE.MeshStandardMaterial;
    Material: THREE.MeshPhysicalMaterial;
    ["Material.010"]: THREE.MeshStandardMaterial;
    ["Material.006"]: THREE.MeshStandardMaterial;
    ["Material.010"]: THREE.MeshStandardMaterial;
    ["Material.007"]: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshPhysicalMaterial;
  };
};

type Props = {
  children: ReactNode;
  sceneType?: "Shoes" | "Cases";
} & Omit<JSX.IntrinsicElements["group"], "children">;

export function Model({ children, sceneType = "Shoes", ...props }: Props) {
  const { nodes, materials } = useGLTF("/models/shore/shore.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      {children}
      <RigidBody type="fixed" colliders="trimesh">
        <group
          position={[-2.287, 0, -1.453]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            geometry={nodes.Office2_Books1.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_Books10.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_Books11.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_Books12.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_Books13.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_Books14.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_Books15.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_Books16.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_Books2.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_Books3.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_Books4.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_Books5.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_Books6.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_Books7.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_Books8.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_Books9.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_box_1.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_box_2.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_box_3.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_box_4.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_box_5.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_box_6.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_box_7.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_carpet.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_chair.geometry}
            material={materials.LP_Rooms}
            position={[0, -61.57, 0]}
          />
          <mesh
            geometry={nodes.Office2_clock_1.geometry}
            material={materials.LP_Rooms}
            position={[-29.086, 0, 0]}
          />
          <mesh
            geometry={nodes.Office2_decoration1.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_decoration2.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_Flower.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_Keyboard.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_little_table.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_magazines1.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_magazines2.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_magazines3.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_magazines4.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_magazines5.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_monitor1.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_Mouse.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_parquet1.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_parquet2.geometry}
            material={materials.LP_Rooms}
            position={[-29.415, 17.469, 0]}
            scale={[1, 1.271, 1]}
          />
          <mesh
            geometry={nodes.Office2_parquet2001.geometry}
            material={materials.LP_Rooms}
            position={[872.712, 15.884, -2.889]}
            scale={[1, 1.291, 1]}
          />
          <mesh
            geometry={nodes.Office2_parquet2002.geometry}
            material={materials.LP_Rooms}
            position={[148, -496.13, -2.889]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[1, 1.93, 1]}
          />
          <mesh
            geometry={nodes.Office2_Pens.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_Photoframe1.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_Photoframe_2.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_Photoframe_3.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_Photoframe_4.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_picture.geometry}
            material={materials.LP_Rooms}
            position={[-31.621, 0, 0]}
          />
          <mesh
            geometry={nodes.Office2_Room_Paper.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_shelves.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_sofa.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_stand.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_table.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_vial_1.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_vial_2.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_Vinyl_players.geometry}
            material={materials.LP_Rooms}
          />
          <mesh
            geometry={nodes.Office2_Vinyls.geometry}
            material={materials.LP_Rooms}
          />
        </group>
        <pointLight
          intensity={1.853}
          decay={2}
          color="#ffe492"
          position={[-3.283, 6.564, 4.494]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1.371, 1.454, 1.276]}
        />
        <group position={[0, -1.261, 0]} scale={[5.484, 5.105, 5.818]}>
          <mesh
            geometry={nodes.Plane002_1.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            geometry={nodes.Plane002_2.geometry}
            material={materials["Material.005"]}
          />
        </group>
        <mesh
          geometry={nodes.Plane004.geometry}
          material={materials["Material.003"]}
          position={[0, -1.386, 0]}
          scale={[5.484, 5.105, 5.818]}
        />
        <mesh
          geometry={nodes.Plane005.geometry}
          material={nodes.Plane005.material}
          position={[0, -1.261, 0]}
          scale={[5.484, 5.105, 5.818]}
        />
        <mesh
          geometry={nodes.Plane006.geometry}
          material={materials["Material.009"]}
          position={[0, -1.413, 0]}
          scale={[5.484, 5.105, 5.818]}
        />
        <mesh
          geometry={nodes.Plane007.geometry}
          material={materials["Material.006"]}
          position={[0, -1.261, 0]}
          scale={[5.484, 5.105, 5.818]}
        >
          <mesh
            geometry={nodes.Left_Window.geometry}
            material={materials.Material}
            position={[-0.576, 0.698, 0.303]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.182, 0.172, 0.108]}
          />
          <mesh
            geometry={nodes.Right_Window_.geometry}
            material={materials.Material}
            position={[0.43, 0.698, 0.303]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.182, 0.172, 0.108]}
          />
        </mesh>
        <mesh
          geometry={nodes.Plane008.geometry}
          material={materials["Material.006"]}
          position={[-0.1, -1.261, 3.5]}
          rotation={[Math.PI, -1.396, Math.PI]}
          scale={[5.484, 5.105, 5.818]}
        />
        <mesh
          geometry={nodes.Plane009.geometry}
          material={materials["Material.010"]}
          position={[0, -1.261, 0]}
          scale={[5.484, 5.105, 5.818]}
        />
        <mesh
          geometry={nodes.Plane010.geometry}
          material={materials["Material.010"]}
          position={[0, -1.261, 0]}
          scale={[5.484, 5.105, 5.818]}
        />
        <mesh
          geometry={nodes.Plane003.geometry}
          material={materials["Material.003"]}
          position={[-3.119, 5.226, 2.414]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.614, 0.998, 0.571]}
        >
          {sceneType === "Shoes" ? (
            <mesh
              geometry={nodes.Text006.geometry}
              material={materials["Material.006"]}
              position={[-0.071, -0.303, 0.1]}
              scale={2.233}
            />
          ) : (
            <mesh
              geometry={nodes.Text.geometry}
              material={materials["Material.006"]}
              position={[-0.071, -0.303, 0.1]}
              scale={2.233}
            />
          )}
        </mesh>
        <mesh
          geometry={nodes.Plane011.geometry}
          material={materials["Material.003"]}
          position={[-1.761, 5.226, 2.414]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.614, 0.998, 0.571]}
        >
          {sceneType === "Shoes" ? (
            <mesh
              geometry={nodes.Text007.geometry}
              material={materials["Material.006"]}
              position={[0.007, -0.303, 0.1]}
              scale={2.233}
            />
          ) : (
            <mesh
              geometry={nodes.Text001.geometry}
              material={materials["Material.006"]}
              position={[0.007, -0.303, 0.1]}
              scale={2.233}
            />
          )}
        </mesh>
        <mesh
          geometry={nodes.Plane012.geometry}
          material={materials["Material.003"]}
          position={[-0.404, 5.226, 2.414]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.614, 0.998, 0.571]}
        >
          {sceneType === "Shoes" ? (
            <mesh
              geometry={nodes.Text008.geometry}
              material={materials["Material.006"]}
              position={[-0.071, -0.303, 0.1]}
              scale={2.233}
            />
          ) : (
            <mesh
              geometry={nodes.Text002.geometry}
              material={materials["Material.006"]}
              position={[-0.071, -0.303, 0.1]}
              scale={2.233}
            />
          )}
        </mesh>
        <mesh
          geometry={nodes.Plane013.geometry}
          material={materials["Material.003"]}
          position={[0.953, 5.226, 2.414]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.614, 0.998, 0.571]}
        >
          <mesh
            geometry={nodes.Text003.geometry}
            material={materials["Material.006"]}
            position={[-0.071, -0.303, 0.1]}
            scale={2.233}
          />
        </mesh>
        <mesh
          geometry={nodes.Plane014.geometry}
          material={materials["Material.003"]}
          position={[2.311, 5.226, 2.414]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.614, 0.998, 0.571]}
        >
          <mesh
            geometry={nodes.Text004.geometry}
            material={materials["Material.006"]}
            position={[-0.071, -0.303, 0.1]}
            scale={2.233}
          />
        </mesh>
        <group position={[-3.899, -0.06, 4.609]} scale={[0.584, 0.544, 0.62]}>
          <mesh
            geometry={nodes.Circle002_1.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            geometry={nodes.Circle002_2.geometry}
            material={materials["Material.007"]}
          />
        </group>
        <mesh
          geometry={nodes.Plane.geometry}
          material={materials["Material.002"]}
          position={[-1.48, 1.85, 2.81]}
          rotation={[Math.PI / 2, 0, 1.745]}
          scale={[0.55, 1, 1]}
        />
      </RigidBody>
    </group>
  );
}

useGLTF.preload("/models/shore/shore.glb");
